'use strict';
const C=JSON.parse(document.getElementById('catalog').textContent), app=document.getElementById('app-main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const link=(t,id='')=>'#trip/'+encodeURIComponent(t.id)+(id?'/'+encodeURIComponent(id):'');
const country=id=>C.countries.find(c=>c.id===id), trip=id=>C.trips.find(t=>t.id===id);
const storageKey='roger-travel-notebook-v1';let state={saved:[],notes:{},checks:{},large:false},storageOK=true,activeTrip=null,guideReturnHref=null;
try{const p=JSON.parse(localStorage.getItem(storageKey)||'null');if(p&&Array.isArray(p.saved)&&p.notes&&p.checks)state={...state,...p};}catch(e){storageOK=false;}
function toast(s){const n=document.getElementById('toast');n.textContent=s;n.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.classList.remove('show'),4200);}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state));storageOK=true;return true;}catch(e){storageOK=false;toast('瀏覽器無法儲存，請匯出備份；目前資料仍可暫時使用。');return false;}}
document.body.classList.remove('large-text');
const records=[];
C.trips.forEach(t=>{const temp=document.getElementById('content-'+t.id);temp.content.querySelectorAll('.slot,details.guide-card,section[id]').forEach(el=>{const heading=el.querySelector('h2,h3,summary');if(!heading||!el.id)return;records.push({trip:t.id,id:el.id,title:heading.textContent.trim(),text:el.textContent.replace(/\s+/g,' ').trim(),type:el.matches('details')?'景點導覽':el.matches('.slot')?'行程景點':'行程章節'});});});
const recordKey=r=>r.trip+'::'+r.id;
function crumb(items){return '<div class="crumb"><a href="#home">國家首頁</a>'+items.map(i=>' <span>/</span> '+(i.href?'<a href="'+i.href+'">'+esc(i.label)+'</a>':'<span>'+esc(i.label)+'</span>')).join('')+'</div>';}
function searchForm(q=''){return '<form class="searchform" id="search-form"><input id="search-input" name="q" aria-label="搜尋國家、城市或景點" placeholder="搜尋國家、城市或景點，例如 Sarajevo、刺殺" value="'+esc(q)+'" type="search"><button class="primary" type="submit">搜尋</button></form>';}
function tripCard(t){return '<article class="trip-card"><div class="date-block">'+esc(t.start.slice(5).replace('-','/'))+' — '+esc(t.end.slice(5).replace('-','/'))+'<small>'+esc(t.start.slice(0,4))+' · '+t.days.length+' 天</small></div><div><h3><a href="'+link(t)+'">'+esc(t.title)+'</a></h3><p>'+esc(t.subtitle)+'</p><div>'+t.tags.map(x=>'<span class="badge">'+esc(x)+'</span>').join('')+'<span class="badge">'+esc(t.status)+'</span></div><small>內容查核 '+esc(t.verified)+' · '+t.countries.map(id=>esc(country(id).english)).join(' / ')+'</small></div><a class="btn primary" href="'+link(t)+'">查看行程</a></article>';}
function home(){activeTrip=null;document.title=C.site.title;app.innerHTML='<div class="section-head country-heading"><h2>探索國家</h2><span class="muted">'+C.site.updated+' 更新網站</span></div><div class="countries">'+C.countries.map(c=>{const ts=C.trips.filter(t=>t.countries.includes(c.id));return '<a class="country-card" href="#country/'+c.id+'"><div class="country-top"><span class="country-code">'+esc(c.code)+'</span><span class="country-meta">'+esc(c.region)+' · '+ts.length+' 份行程</span></div><h3>'+esc(c.english)+'</h3><p>'+esc(c.summary)+'</p><div class="country-bottom"><span>'+esc(c.coverage?'查看收錄範圍':ts.map(t=>t.days.length+' 天行程').join('、'))+'</span><b>查看國家 →</b></div></a>';}).join('')+'</div><div class="section-head"><h2>已收錄行程</h2><a href="#saved">我的收藏</a></div>'+C.trips.map(tripCard).join('')+'<div class="panel tint"><h3>行前準備，一起帶著走</h3><p>按日期查閱每日安排，點開地圖與導覽。收藏只儲存在目前瀏覽器。</p><a href="#tools">下載離線版本與備份個人資料 →</a></div>';}
function countryPage(id){const c=country(id);if(!c)return missing();activeTrip=null;document.title=c.english+'｜'+C.site.title;const ts=C.trips.filter(t=>t.countries.includes(id));app.innerHTML=crumb([{label:c.english}])+'<h1>'+esc(c.english)+'</h1><p>'+esc(c.summary)+'</p><div class="country-facts"><div><small>地區</small>'+esc(c.region)+'</div><div><small>貨幣</small>'+esc(c.currency)+'</div><div><small>時區</small>'+esc(c.timeZone)+'</div><div><small>行程</small>'+ts.length+' 份</div></div>'+(c.coverage?'<div class="status-note">'+esc(c.coverage)+'</div>':'')+'<h2>行程規畫</h2>'+ts.map(tripCard).join('')+'<p class="muted">跨國行程會同時列在相關國家；內容共用同一份，方便沿路接續閱讀。</p>';}
function savedButton(r){const yes=state.saved.includes(recordKey(r));return '<button class="bookmark" data-save="'+esc(recordKey(r))+'" aria-pressed="'+yes+'" aria-label="'+(yes?'取消收藏':'收藏')+'：'+esc(r.title)+'">'+(yes?'★ 已收藏':'☆ 收藏')+'</button>';}
function mountTrip(t){activeTrip=t.id;guideReturnHref=null;document.title=t.title+'｜'+C.site.title;
app.innerHTML=crumb([{label:country(t.countries[0]).english,href:'#country/'+t.countries[0]},{label:t.title}])+'<div class="trip-intro"><div class="eyebrow">'+esc(t.start)+' — '+esc(t.end)+'</div><h1>'+esc(t.title)+'</h1></div><div class="trip-toolbar no-print"><select id="day-jump" aria-label="跳到日期"><option value="">選擇日期</option>'+t.days.map(d=>'<option value="'+esc(d.id)+'">'+esc(d.date.slice(5).replace('-','/'))+' · '+esc(d.label)+'</option>').join('')+'</select></div>'+(t.important?'<div class="panel tint"><strong>路線重點</strong><p>'+esc(t.important)+'</p></div>':'')+'<div class="legacy" id="legacy"></div>';
const legacy=document.getElementById('legacy');legacy.append(document.getElementById('content-'+t.id).content.cloneNode(true));
legacy.querySelectorAll('a[href^="#"]').forEach(a=>{const id=a.getAttribute('href').slice(1);if(id.startsWith('trip/'))return;a.href=link(t,id);if(a.classList.contains('guide-link')){const r=records.find(r=>r.trip===t.id&&r.id===id);a.textContent='導覽';a.setAttribute('aria-label','導覽：'+(r?.title||id));a.title=r?.title||'景點導覽';}});
legacy.querySelectorAll('[data-map]').forEach(a=>{a.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a.dataset.map);a.target='_blank';a.rel='noopener noreferrer';});
const rp=legacy.querySelector('#route');if(rp){['Sarajevo Bosnia and Herzegovina','Foca Bosnia and Herzegovina','Hum border crossing Bosnia Montenegro','Scepan Polje Montenegro','Pluzine Montenegro','Piva Monastery Montenegro','Jasenovo Polje Niksic Montenegro','Savnik Montenegro','Zabljak Montenegro'].forEach((p,i)=>{const a=document.createElement('a');a.className='map';a.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p);a.textContent=(i+1)+'. '+p;a.target='_blank';a.rel='noopener noreferrer';rp.append(a);});}
records.filter(r=>r.trip===t.id&&r.type!=='行程章節').forEach(r=>{const el=legacy.querySelector('[id="'+CSS.escape(r.id)+'"]');if(!el)return;const wrap=document.createElement('div');wrap.className='no-print';wrap.innerHTML=savedButton(r);if(el.matches('details'))el.append(wrap);else(el.children[1]||el).append(wrap);});
legacy.querySelectorAll('a[target="_blank"]').forEach(a=>a.rel='noopener noreferrer');
}
function showTarget(id){if(!id){window.scrollTo(0,0);return;}const el=document.getElementById(id);if(!el)return;let p=el;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}requestAnimationFrame(()=>el.scrollIntoView({block:'start'}));const sel=document.getElementById('day-jump');if(sel)sel.value=trip(activeTrip).days.some(d=>d.id===id)?id:'';}
function resultCard(r){const t=trip(r.trip);return '<article class="result"><div class="result-meta">'+esc(t.title)+' · '+esc(r.type)+'</div><h3><a href="'+link(t,r.id)+'">'+esc(r.title)+'</a></h3><p>'+esc(r.text.slice(0,155))+'…</p>'+savedButton(r)+'</article>';}
function search(q){activeTrip=null;document.title='搜尋｜'+C.site.title;const qs=norm(q.trim()).split(/\s+/).filter(Boolean);const matches=qs.length?records.filter(r=>qs.every(w=>norm(r.title+' '+r.text+' '+trip(r.trip).title+' '+trip(r.trip).countries.map(id=>country(id).name+' '+country(id).english).join(' ')).includes(w))):[];const cs=q.trim()?C.countries.filter(c=>qs.every(w=>norm(c.name+' '+c.english+' '+c.summary).includes(w))):[];app.innerHTML=crumb([{label:'搜尋'}])+'<h1>找一個地方，或一段故事。</h1>'+searchForm(q)+'<p class="search-hint">可用中文、地名原文或關鍵字搜尋全部已收錄內容。</p>'+(q.trim()?'<p role="status" class="muted">找到 '+matches.length+' 筆內容'+(cs.length?'、'+cs.length+' 個國家':'')+'</p>'+cs.map(c=>'<div class="panel"><a href="#country/'+c.id+'">'+esc(c.english)+'</a></div>').join('')+matches.map(resultCard).join('')+(matches.length||cs.length?'':'<div class="empty">沒有符合的內容。試試「Sarajevo」、「刺殺」或「Piva」。</div>'):'<div class="panel"><h3>從這些主題開始</h3><div class="actions">'+['Sarajevo','刺殺','Haggadah','Piva','停車','午餐'].map(q=>'<a class="btn" href="#search?q='+encodeURIComponent(q)+'">'+q+'</a>').join('')+'</div></div>');}
function saved(){activeTrip=null;document.title='收藏｜'+C.site.title;const rs=records.filter(r=>state.saved.includes(recordKey(r)));app.innerHTML=crumb([{label:'我的收藏'}])+'<h1>我的收藏</h1><p class="muted">只儲存在目前瀏覽器；分享網站連結不會包含你的收藏或筆記。</p>'+ (rs.length?rs.map(resultCard).join(''):'<div class="empty"><h2>把想去的地方留在這裡。</h2><p>進入行程，點景點或導覽旁的「☆ 收藏」。</p><a class="btn" href="#home">查看國家</a></div>')+'<a href="#tools">匯出或還原個人資料 →</a>';}
function toolsPage(){activeTrip=null;document.title='旅行工具｜'+C.site.title;app.innerHTML=crumb([{label:'旅行工具'}])+'<h1>行程帶著走。</h1><div class="two-col"><div class="utility-card"><h2>離線行程</h2><p>下載整站 HTML，在支援 JavaScript 的瀏覽器開啟即可閱讀內文。地圖導航、官方網站與即時天氣仍需要網路。</p><button class="primary" data-download>下載整站 HTML</button><p class="muted">手機若只能預覽檔案，可使用瀏覽器的列印功能保存 PDF。下載不會包含個人筆記與收藏。</p></div><div class="utility-card"><h2>個人資料備份</h2><p>收藏及舊版留下的清單、筆記只存在目前瀏覽器。換手機或清除瀏覽資料前，先匯出備份。</p><div class="actions"><button data-export>匯出備份</button><label class="btn" for="import-state">還原備份</label><input hidden id="import-state" type="file" accept="application/json,.json"></div><p class="muted">還原會合併收藏，並以備份內的同名筆記和勾選覆蓋目前內容。</p></div></div><div class="panel"><h2>在旅途中少找一步</h2><ul><li>在每份行程上方選日期，直接跳到當天安排。</li><li>「導覽」可打開景點背景；地圖按鍵可轉到 Google Maps。</li><li>複製瀏覽器網址即可分享目前行程章節。</li><li>若需保存 PDF，可使用瀏覽器的列印功能，導覽內文會自動展開。</li></ul></div>';}
function about(){activeTrip=null;document.title='使用說明｜'+C.site.title;app.innerHTML=crumb([{label:'使用說明'}])+'<h1>把旅行經驗，一份份留下。</h1><div class="panel"><h2>怎麼使用</h2><p>從國家選行程，再按日期看每日安排。跨國行程共用同一份內容，從任一相關國家都能找到。</p><p>時間、門票與天氣均以每份行程標示的查核日期為準。網站不會自動取得最新預報、路況或營業時間；出發前請用內文的官方來源核對。</p><p>收藏僅存在目前瀏覽器，沒有帳號或跨裝置同步；舊版的筆記與清單仍可備份。請定期在「旅行工具」匯出備份。</p></div><div class="panel maintenance"><h2>未來新增國家與行程</h2><p>提供國家、旅行日期、交通方式與原始行程，即可依相同模板整理。每份行程都會包含：</p><ul><li>每日時間表、移動方式與停留時間。</li><li>景點介紹、歷史背景、相關故事及 Google Maps 連結。</li><li>門票與餐飲預算，清楚區分已核實價格與估算。</li><li>預約期限、雨天備案、刪減順序及必要安全提醒。</li><li>資訊查核日期、原始來源與待確認事項。</li></ul><p>後續行程由助理整理並發布到這個網站，國家目錄與搜尋會一起更新。</p><a href="https://github.com/rogeryangct/travel-itineraries" target="_blank" rel="noopener">開啟網站儲存庫</a></div><div class="panel"><h2>功能參考</h2><p>參考 <a href="https://play.google.com/store/apps/details?id=com.wanderlog.android" target="_blank" rel="noopener">Wanderlog</a> 的按日規畫與地圖入口，以及 <a href="https://play.google.com/store/apps/details?id=com.tripit" target="_blank" rel="noopener">TripIt</a> 的集中查閱方式。本網站以輕量文字行程為主。</p></div>';}
function localDate(now,timeZone){const p=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const get=k=>p.find(x=>x.type===k).value;return get('year')+'-'+get('month')+'-'+get('day');}
function todayMatches(now=new Date()){return C.trips.flatMap(t=>t.days.filter(d=>d.date===localDate(now,d.timeZone||t.timeZone||country(t.countries[0]).timeZone)).map(d=>({t,d})));}
function todayPage(){const matches=todayMatches();if(matches.length===1){location.replace(link(matches[0].t,matches[0].d.id));return;}activeTrip=null;document.title='今天｜'+C.site.title;app.innerHTML=crumb([{label:'今天'}])+'<h1>今天的行程</h1><p class="muted">以各行程所在地的日期判斷。</p>'+(matches.length?matches.map(({t,d})=>'<article class="panel"><div class="eyebrow">'+esc(d.date)+'</div><h2>'+esc(t.title)+'</h2><p>'+esc(d.label)+'</p><a class="btn primary" href="'+link(t,d.id)+'">查看今天行程</a></article>').join(''):'<div class="empty"><h2>今天沒有已收錄的行程。</h2><p>可以從國家目錄選擇其他日期。</p><a class="btn" href="#home">查看國家</a></div>');window.scrollTo(0,0);}
function missing(){activeTrip=null;app.innerHTML=crumb([{label:'找不到頁面'}])+'<div class="empty"><h1>這一頁還沒收錄。</h1><a class="btn primary" href="#home">回國家首頁</a></div>';}
function route(){let hash;try{hash=decodeURIComponent(location.hash.slice(1));}catch(e){return missing();}const parts=hash.split('/');if(parts[0]==='trip'){const t=trip(parts[1]);if(!t)return missing();if(activeTrip!==t.id)mountTrip(t);showTarget(parts.slice(2).join('/'));return;}if(hash&&document.getElementById('content-'+C.trips[0].id).content.querySelector('[id="'+CSS.escape(hash)+'"]')){location.replace(link(C.trips[0],hash));return;}if(!hash||hash==='home')home();else if(parts[0]==='country')countryPage(parts[1]);else if(hash.startsWith('search'))search(new URLSearchParams(location.hash.split('?')[1]||'').get('q')||'');else if(hash==='today'){todayPage();return;}else if(hash==='visited-countries')visitedCountriesPage();else if(hash.startsWith('history'))historyPage();else if(hash==='saved')saved();else if(hash==='tools')toolsPage();else if(hash==='about')about();else missing();window.scrollTo(0,0);}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function offline(){const doc=document.documentElement.cloneNode(true);doc.querySelector('#app-main').innerHTML='';doc.querySelector('#toast').textContent='';doc.querySelector('#toast').className='';doc.querySelector('body').className='';download('roger-travel-notebook.html','<!doctype html>\n'+doc.outerHTML,'text/html;charset=utf-8');toast('已準備下載整站 HTML。');}
document.addEventListener('submit',e=>{if(e.target.id==='search-form'){e.preventDefault();const q=document.getElementById('search-input').value.trim();location.hash='search?q='+encodeURIComponent(q);}});
document.addEventListener('change',async e=>{const el=e.target;if(el.id==='day-jump'&&el.value)location.hash=link(trip(activeTrip),el.value);if(el.id==='import-state'&&el.files[0]){try{if(el.files[0].size>2e6)throw Error();const data=JSON.parse(await el.files[0].text());if(data.format!=='roger-travel-backup-v1'||!Array.isArray(data.saved)||!data.notes||!data.checks||typeof data.notes!=='object'||typeof data.checks!=='object')throw Error();state.saved=[...new Set([...state.saved,...data.saved.filter(x=>typeof x==='string')])];for(const [k,v] of Object.entries(data.notes))if(typeof v==='string'&&!['__proto__','constructor','prototype'].includes(k))state.notes[k]=v;for(const [k,v] of Object.entries(data.checks))if(typeof v==='boolean'&&!['__proto__','constructor','prototype'].includes(k))state.checks[k]=v;persist();toast('已還原個人資料。');}catch(err){toast('無法還原：請選擇本站匯出的 JSON 備份。');}el.value='';}});
let printOpen=[];
function expandForPrint(){printOpen=[...document.querySelectorAll('.legacy details')].map(d=>[d,d.open]);printOpen.forEach(([d])=>d.open=true);}
addEventListener('beforeprint',expandForPrint);addEventListener('afterprint',()=>{printOpen.forEach(([d,o])=>d.open=o);printOpen=[];});
document.addEventListener('click',async e=>{const anchor=e.target.closest('a');if(anchor?.getAttribute('href')==='#today'){e.preventDefault();if(location.hash==='#today')todayPage();else location.hash='today';return;}if(anchor?.classList.contains('skip')){e.preventDefault();app.focus();app.scrollIntoView();return;}if(anchor?.classList.contains('guide-link')&&activeTrip){const origin=anchor.closest('.slot[id],section[id]');guideReturnHref=link(trip(activeTrip),origin?.id||'');}if(anchor?.classList.contains('guide-return')&&guideReturnHref){e.preventDefault();location.hash=guideReturnHref;return;}const b=e.target.closest('button');if(b?.dataset.save){const k=b.dataset.save;state.saved=state.saved.includes(k)?state.saved.filter(x=>x!==k):[...state.saved,k];persist();document.querySelectorAll('[data-save]').forEach(n=>{if(n.dataset.save!==k)return;const yes=state.saved.includes(k);n.textContent=yes?'★ 已收藏':'☆ 收藏';n.setAttribute('aria-pressed',yes);n.setAttribute('aria-label',(yes?'取消收藏':'收藏')+'：'+(records.find(r=>recordKey(r)===k)?.title||''));});if(location.hash==='#saved')saved();return;}if(b?.hasAttribute('data-download'))offline();if(b?.hasAttribute('data-export'))download('roger-travel-backup.json',JSON.stringify({format:'roger-travel-backup-v1',exported:new Date().toISOString(),saved:state.saved,notes:state.notes,checks:state.checks},null,2),'application/json');const a=e.target.closest('a');if(a?.hash&&a.hash===location.hash&&activeTrip)showTarget(decodeURIComponent(a.hash.split('/').slice(2).join('/')));});
addEventListener('hashchange',route);route();

function measureNavigation(){document.documentElement.style.setProperty('--sitebar-height',document.getElementById('sitebar').getBoundingClientRect().height+'px');}
measureNavigation();if(typeof ResizeObserver!=='undefined')new ResizeObserver(measureNavigation).observe(document.getElementById('sitebar'));else addEventListener('resize',measureNavigation);

